### ISSUE TITLE
Provide API for DSU

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/rvm#148]
DSU requested an API on RVM to automatically import the data from the dashboard (e.g. number of active protocols) to the DSU website.

Create endpoints for:
- [x] #150
- [x] #151

Other relevant issues:
- [x] API access should be authenticated
- [x] Responses should not be paginated
- [x] #153

**Comment by andreiio** [comment]
We need more info before putting this in development:
- a list of the data points to be included
- how are they planning on consuming this api?
- do we need to add authentication to the api?
- how often does the data need to be refreshed?

**Comment by gheorghelupu17** [comment]
+ how do we document the API?
