### ISSUE TITLE
[Organizații/ Profil] implement new sub-section in organization's profile 

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/rvm#176]
Implement a new sub-section called "Persoană de contact pentru Platforma Teams ‘Sprijin Umanitar DSU-GOV / FiiPregătit" in "Profil" tab.
The section should include the following fields:
Nume (Text/String [string] 50 characters max)
Prenume (Text/String [string] 50 characters max)
Email (Text/String [string] 50 characters max)
Telefon (Numeric [numeric] 14 characters max)
Rol (Text/String [string] 50 characters max)

Group the fields in a sub-section exactly how the "Persoană de contact în relația cu DSU" seb-section is designed now.
Place the sub-section right after the "Persoană de contact în relația cu DSU" seb-section

**Comment by alexPopaCode4** [comment]
Hello, fields for contact person for DSU  are limited to 100 characters for first name and last name and limited at 200 characters for role and email. It's strange to use different limits for same fields. I use here same limits from DSU or change DSU limits?
