### ISSUE TITLE
[Iconography] suitable icons for side nav bar 

### ISSUE THREAD

**Issue by teodoranegru** [code4romania/rvm#43]
The side navigation bar consists of 6 buttons: 'Panoul de control', 'Documents', Organisations', 'Resources', 'Users', 'Volunteers'; 
The architecture of each button consists of an icon and the label. 
Currently, the used icons don't suit the label. To be discussed, depending on the available icons library, which icons are best for each button. 
![image](https://github.com/code4romania/rvm/assets/102228836/96ab9278-1823-48c4-b9fd-40dc066411c6)

**Comment by andreiio** [comment]
Current version:
<img width="235" alt="Screenshot 2023-06-30 at 17 48 53" src="https://github.com/code4romania/rvm/assets/1569300/ca6b1cff-e881-4344-9f59-dc6928b2f97b">

We can use any of these icons: https://v1.heroicons.com/
