### ISSUE TITLE
[Infra] Docker image on Docker Hub missing `latest` tag

### ISSUE THREAD

**Issue by LucianU** [code4romania/rvm#67]
The README instructs the user to run: 
```
docker run --rm -it code4romania/rvm php artisan key:generate --show
``` 
as part of the initial setup. If that command doesn't find a local image named `code4romania/rvm`, it tries to pull from Docker Hub `code4romania/rvm:latest`. But on Docker Hub, there is no image with that tag, only one with the `edge` tag.

**Comment by andreiio** [comment]
The `latest` tag will be published as soon as [a release is tagged](https://github.com/docker/metadata-action#latest-tag).

I added the missing dev environment instructions in #69, which don't require running commands off of a published image.
